[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["go mod download && npm --prefix web install"]

[phases.build]
cmds = ["npm --prefix web run build && go build -ldflags='-w -s' -o out ./cmd/producer"]

[start]
cmd = "./out"
