[phases.setup]
nixPkgs = ["nodejs_20"]

[variables]
NPM_CONFIG_PRODUCTION = "false"

[phases.install]
cmds = [
  "go mod download",
  "npm --prefix web ci --include=dev"
]

[phases.build]
cmds = [
  "npm --prefix web run build",
  "test -f web/dist/index.html",
  "go build -ldflags='-w -s' -o out ./cmd/producer"
]

[start]
cmd = "./out"
