FROM golang:1.22-alpine AS builder
WORKDIR /build
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o producer ./cmd/producer

FROM alpine:3.20
RUN apk add --no-cache ca-certificates
COPY --from=builder /build/producer /app/producer
EXPOSE 8080
CMD ["/app/producer"]
